refactor: exclude config knowledge base from guide
MapColonies/infops-portal pull request #13
Opened 2024-10-06 08:32 UTC by netanelC

2024-10-07 05:05 UTC, CptSchnitz commented
i would put it as the readme of the config management folder instead of a different page

2024-10-14 14:00 UTC, CptSchnitz requested changes

2024-10-14 14:00 UTC, CptSchnitz commented on docs/knowledge-base/config-management/what-is-it.mdx
> +### Config Management is the complete solution to manage all the configuration needs of MapColonies.
This shouldn't be a title, just normal text

2024-10-14 14:00 UTC, CptSchnitz commented on docs/knowledge-base/config-management/img/config-management-architecture.png
Use export instead of print screen to remove the grid

2024-10-14 14:00 UTC, CptSchnitz commented on docs/knowledge-base/config-management/what-is-it.mdx
I would put this file as the readme of config management instead of a separate file.

2024-10-14 14:00 UTC, CptSchnitz commented on docs/knowledge-base/config-management/what-is-it.mdx
> +Now you can see the [zero to hero doc](../guides/config-management/zero-to-hero.mdx) and integrate this system in your service!
I would add a title for this part like `whats next?` and a list of stuff

2024-10-14 16:10 UTC, netanelC commented on docs/knowledge-base/config-management/what-is-it.mdx
> +### Config Management is the complete solution to manage all the configuration needs of MapColonies.
Refactored

2024-10-14 16:12 UTC, netanelC commented on docs/knowledge-base/config-management/img/config-management-architecture.png
Done

2024-10-14 16:12 UTC, netanelC commented on docs/knowledge-base/config-management/what-is-it.mdx
Done

2024-10-14 16:21 UTC, netanelC commented on docs/knowledge-base/config-management/what-is-it.mdx
> +Now you can see the [zero to hero doc](../guides/config-management/zero-to-hero.mdx) and integrate this system in your service!
Done

2024-10-15 05:52 UTC, CptSchnitz approved these changes

2024-10-15 07:17 UTC, merged